version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - sphinx>=4.5
        - sphinx-rtd-theme>=1.0.0
        - sphinx-autodoc-typehints>=1.12.0
        - myst-parser>=0.18.0
        - nbsphinx>=0.8.0
        - docutils>=0.17
        - recommonmark>=0.7.0

sphinx:
  builder: html
  configuration: docs/sphinx/conf.py
  fail_on_warning: false
