services:
  migrations:
    build: .
    volumes:
      - ./config:/app/config:ro
    environment:
      DATABASE_URL: postgresql+psycopg2://simdb:simdb@postgres:5432/simdb
    depends_on:
      - postgres
    command: uv run alembic upgrade head
    restart: "no"

  web:
    build: .
    environment:
      IMAS_LOCAL_HOSTS: localhost
    ports:
      - "5000:5000"
    volumes:
      - ./validation:/app/validation:ro
      - ./config:/app/config:ro
      - ./tmp/partition_data:/data/simdb/partition:ro
      - ./upload_folder:/data/simdb/simulations
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    restart: unless-stopped

  worker:
    profiles: [with_workers]
    # docker compose --profile with_workers enables this service
    build: .
    command: uv run simdb_worker
    volumes:
      - ./config:/app/config:ro
      - ./tmp/partition_data:/data/simdb/partition:ro
      - ./upload_folder:/data/simdb/simulations
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    restart: unless-stopped

  beat:
    profiles: [with_workers]
    # docker compose --profile with_workers enables this service
    build: .
    command: uv run simdb_beat
    volumes:
      - ./config:/app/config:ro
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=simdb
      - POSTGRES_PASSWORD=simdb
      - POSTGRES_DB=simdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U simdb"]
      interval: 1s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
