"""initial migration

Revision ID: c84b85ae4bed
Revises: 
Create Date: 2026-02-10 15:24:11.323077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from simdb.database.models.types import UUID, ChoiceType
from simdb.notifications import Notification

# revision identifiers, used by Alembic.
revision: str = 'c84b85ae4bed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define notification choices
NOTIFICATION_CHOICES = {
    Notification.VALIDATION: "V",
    Notification.REVISION: "R",
    Notification.OBSOLESCENCE: "O",
    Notification.ALL: "A",
}

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', UUID(), nullable=False),
    sa.Column('alias', sa.String(length=250), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_alias'), 'simulations', ['alias'], unique=True)
    op.create_index(op.f('ix_simulations_uuid'), 'simulations', ['uuid'], unique=True)
    op.create_table('watchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=1000), nullable=True),
    sa.Column('notification', ChoiceType(choices=NOTIFICATION_CHOICES, length=1, enum_type=Notification), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sim_id', sa.Integer(), nullable=True),
    sa.Column('element', sa.String(length=250), nullable=False),
    sa.Column('value', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['sim_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_sim_id'), 'metadata', ['sim_id'], unique=False)
    op.create_index('metadata_index', 'metadata', ['sim_id', 'element'], unique=True)
    op.create_table('simulation_input_files',
    sa.Column('simulation_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], )
    )
    op.create_table('simulation_output_files',
    sa.Column('simulation_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], )
    )
    op.create_table('simulation_watchers',
    sa.Column('simulation_id', sa.Integer(), nullable=True),
    sa.Column('watcher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['watcher_id'], ['watchers.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_watchers')
    op.drop_table('simulation_output_files')
    op.drop_table('simulation_input_files')
    op.drop_index('metadata_index', table_name='metadata')
    op.drop_index(op.f('ix_metadata_sim_id'), table_name='metadata')
    op.drop_table('metadata')
    op.drop_table('watchers')
    op.drop_index(op.f('ix_simulations_uuid'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_alias'), table_name='simulations')
    op.drop_table('simulations')
    # ### end Alembic commands ###
